// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace h4x0r.MessagesInternal
{

using global::System;
using global::FlatBuffers;

public enum MessageContainer : byte
{
 NONE = 0,
 CreateAccountMessage = 1,
 LoginMessage = 2,
};

public struct MessageBase : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static MessageBase GetRootAsMessageBase(ByteBuffer _bb) { return GetRootAsMessageBase(_bb, new MessageBase()); }
  public static MessageBase GetRootAsMessageBase(ByteBuffer _bb, MessageBase obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public MessageBase __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MessageContainer DataType { get { int o = __p.__offset(4); return o != 0 ? (MessageContainer)__p.bb.Get(o + __p.bb_pos) : MessageContainer.NONE; } }
  public TTable? Data<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o) : null; }

  public static Offset<MessageBase> CreateMessageBase(FlatBufferBuilder builder,
      MessageContainer data_type = MessageContainer.NONE,
      int dataOffset = 0) {
    builder.StartObject(2);
    MessageBase.AddData(builder, dataOffset);
    MessageBase.AddDataType(builder, data_type);
    return MessageBase.EndMessageBase(builder);
  }

  public static void StartMessageBase(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddDataType(FlatBufferBuilder builder, MessageContainer dataType) { builder.AddByte(0, (byte)dataType, 0); }
  public static void AddData(FlatBufferBuilder builder, int dataOffset) { builder.AddOffset(1, dataOffset, 0); }
  public static Offset<MessageBase> EndMessageBase(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MessageBase>(o);
  }
  public static void FinishMessageBaseBuffer(FlatBufferBuilder builder, Offset<MessageBase> offset) { builder.Finish(offset.Value); }
};

public struct CreateAccountMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CreateAccountMessage GetRootAsCreateAccountMessage(ByteBuffer _bb) { return GetRootAsCreateAccountMessage(_bb, new CreateAccountMessage()); }
  public static CreateAccountMessage GetRootAsCreateAccountMessage(ByteBuffer _bb, CreateAccountMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CreateAccountMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Username { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUsernameBytes() { return __p.__vector_as_arraysegment(4); }
  public string Email { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetEmailBytes() { return __p.__vector_as_arraysegment(6); }
  public string Password { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(8); }

  public static Offset<CreateAccountMessage> CreateCreateAccountMessage(FlatBufferBuilder builder,
      StringOffset usernameOffset = default(StringOffset),
      StringOffset emailOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset)) {
    builder.StartObject(3);
    CreateAccountMessage.AddPassword(builder, passwordOffset);
    CreateAccountMessage.AddEmail(builder, emailOffset);
    CreateAccountMessage.AddUsername(builder, usernameOffset);
    return CreateAccountMessage.EndCreateAccountMessage(builder);
  }

  public static void StartCreateAccountMessage(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddUsername(FlatBufferBuilder builder, StringOffset usernameOffset) { builder.AddOffset(0, usernameOffset.Value, 0); }
  public static void AddEmail(FlatBufferBuilder builder, StringOffset emailOffset) { builder.AddOffset(1, emailOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(2, passwordOffset.Value, 0); }
  public static Offset<CreateAccountMessage> EndCreateAccountMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CreateAccountMessage>(o);
  }
};

public struct LoginMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LoginMessage GetRootAsLoginMessage(ByteBuffer _bb) { return GetRootAsLoginMessage(_bb, new LoginMessage()); }
  public static LoginMessage GetRootAsLoginMessage(ByteBuffer _bb, LoginMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LoginMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Username { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUsernameBytes() { return __p.__vector_as_arraysegment(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<LoginMessage> CreateLoginMessage(FlatBufferBuilder builder,
      StringOffset usernameOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset)) {
    builder.StartObject(2);
    LoginMessage.AddPassword(builder, passwordOffset);
    LoginMessage.AddUsername(builder, usernameOffset);
    return LoginMessage.EndLoginMessage(builder);
  }

  public static void StartLoginMessage(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddUsername(FlatBufferBuilder builder, StringOffset usernameOffset) { builder.AddOffset(0, usernameOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static Offset<LoginMessage> EndLoginMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoginMessage>(o);
  }
};

public struct LoginSuccessfulMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LoginSuccessfulMessage GetRootAsLoginSuccessfulMessage(ByteBuffer _bb) { return GetRootAsLoginSuccessfulMessage(_bb, new LoginSuccessfulMessage()); }
  public static LoginSuccessfulMessage GetRootAsLoginSuccessfulMessage(ByteBuffer _bb, LoginSuccessfulMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LoginSuccessfulMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Placeholder { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<LoginSuccessfulMessage> CreateLoginSuccessfulMessage(FlatBufferBuilder builder,
      bool placeholder = false) {
    builder.StartObject(1);
    LoginSuccessfulMessage.AddPlaceholder(builder, placeholder);
    return LoginSuccessfulMessage.EndLoginSuccessfulMessage(builder);
  }

  public static void StartLoginSuccessfulMessage(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPlaceholder(FlatBufferBuilder builder, bool placeholder) { builder.AddBool(0, placeholder, false); }
  public static Offset<LoginSuccessfulMessage> EndLoginSuccessfulMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoginSuccessfulMessage>(o);
  }
};

public struct LoginFailedMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LoginFailedMessage GetRootAsLoginFailedMessage(ByteBuffer _bb) { return GetRootAsLoginFailedMessage(_bb, new LoginFailedMessage()); }
  public static LoginFailedMessage GetRootAsLoginFailedMessage(ByteBuffer _bb, LoginFailedMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LoginFailedMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Placeholder { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<LoginFailedMessage> CreateLoginFailedMessage(FlatBufferBuilder builder,
      bool placeholder = false) {
    builder.StartObject(1);
    LoginFailedMessage.AddPlaceholder(builder, placeholder);
    return LoginFailedMessage.EndLoginFailedMessage(builder);
  }

  public static void StartLoginFailedMessage(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddPlaceholder(FlatBufferBuilder builder, bool placeholder) { builder.AddBool(0, placeholder, false); }
  public static Offset<LoginFailedMessage> EndLoginFailedMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoginFailedMessage>(o);
  }
};


}
